kind: Route
apiVersion: route.openshift.io/v1
metadata: 
  name: insights-frontend-started-app
  labels:
    app: insights-frontend-started-app
spec:
  to:
    kind: Service
    name: insights-frontend-started-app
  port:
    targetPort: 8080-tcp
