# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master,  ci-stable, qa-beta, qa-stable, prod-beta, prod-stable]
  pull_request:
    branches: [ master,  ci-stable, qa-beta, qa-stable, prod-beta, prod-stable]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run verify

  build-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build-standalone:prod
    - name: Container image
      # Uses sha for added security since tags can be updated
      uses: elgohr/Publish-Docker-Github-Action@b2f63259b466ca5a4be395c392546de447450334      
      with:
        name: ${{ env.GITHUB_REPOSITORY }}
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: false
        tags: ${ env.GITHUB_REF##*/}
